# Following travis outline from dfm/emcee3

sudo: false

language: python

python:
    - "3.5"

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.5

        - os: osx
          env: PYTHON_VERSION=3.5

install:
    - pip install numpy scipy setuptools pytest pytest-cov coveralls

script:
    - python setup.py test -a "--cov dessn -v"

after_success:
    - coveralls