# Following travis outline from dfm/emcee3

sudo: false

language: c

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.5

        - os: osx
          env: PYTHON_VERSION=3.5

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create --yes -n test python=$PYTHON_VERSION numpy scipy pytest setuptools h5py pip
    - source activate test
    - pip install pytest-cov coveralls emcee

script:
    - python setup.py test -a "--cov dessn -v"

after_success:
    - coveralls
    - |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"/doc
    pwd
    ls
    make clean
    make rst
    make html
    cd "$TRAVIS_BUILD_DIR"
    #git init
    #git checkout -b gh-pages
    #git add .
    #git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    #git push -f -q https://<me>:$GITHUB_API_KEY@github.com/dessn/abc gh-pages &2>/dev/null
  fi