
def get_systematic_mapping():
    res = {
        "HST_CALSPEC_CALIB": r"{\rm HST Calib}",
        "VPEC": r"v_{\rm pec}",
        "SALT2.sys0": r"{\rm SALT}_0",
        "SALT2.sys1": r"{\rm SALT}_1",
        "SALT2.sys2": r"{\rm SALT}_2",
        "SALT2.sys3": r"{\rm SALT}_3",
        "SALT2.sys4": r"{\rm SALT}_4",
        "SALT2.sys5": r"{\rm SALT}_5",
        "SALT2.sys6": r"{\rm SALT}_6",
        "SALT2.sys7": r"{\rm SALT}_7",
        "SALT2.sys8": r"{\rm SALT}_8",
        "SALT2.sys9": r"{\rm SALT}_9",
        "MWEBV_SCALE": r"{\rm MWE}_{B-V}",
        "SF2011-MWEBV": r"{\rm MWE Model}",
        "Fitz99ColorLaw": r"{\rm MWE ColorLaw}",
        "OD94ColorLaw": r"{\rm MWE ColorLaw}",
        "REDSHIFT_BIAS": r"{\rm \delta z }",
        "DES_ZP_g_CALIB": r"\Delta g",
        "DES_ZP_r_CALIB": r"\Delta r",
        "DES_ZP_i_CALIB": r"\Delta i",
        "DES_ZP_z_CALIB": r"\Delta z",
        "DES_lam10_g_CALIB": r"\Delta \lambda_g",
        "DES_lam10_r_CALIB": r"\Delta \lambda_r",
        "DES_lam10_i_CALIB": r"\Delta \lambda_i",
        "DES_lam10_z_CALIB": r"\Delta \lambda_z",
        "CSP_ZP_t_CALIB": r"\Delta t",
        "CSP_ZP_y_CALIB": r"\Delta y",
        "CSP_ZP_z_CALIB": r"\Delta z",
        "CSP_ZP_A_CALIB": r"\Delta A",
        "CSP_ZP_u_CALIB": r"\Delta u",
        "CSP_ZP_v_CALIB": r"\Delta v",
        "CFAK_ZP_gl_CALIB": r"\Delta gl",
        "CFAK_ZP_hm_CALIB": r"\Delta hm",
        "CFAK_ZP_in_CALIB": r"\Delta in",
        "CFAK_ZP_jo_CALIB": r"\Delta jo",
        "CFAF_ZP_p_CALIB": r"\Delta p",
        "CFAF_ZP_q_CALIB": r"\Delta q",
        "CFAF_ZP_r_CALIB": r"\Delta r",
        "CFAF_ZP_s_CALIB": r"\Delta s",
        "CFAS_ZP_b_CALIB": r"\Delta b",
        "CFAS_ZP_c_CALIB": r"\Delta c",
        "CFAS_ZP_d_CALIB": r"\Delta d",
        "CFAS_ZP_e_CALIB": r"\Delta e",
        "CFAO_ZP_CH_CALIB": r"\Delta CH",
        "CFAO_ZP_DI_CALIB": r"\Delta DI",
        "CFAO_ZP_EJ_CALIB": r"\Delta EJ",
        "CFAO_ZP_FK_CALIB": r"\Delta FK",
        "CSP_lam10_t_CALIB": r"\Delta \lambda_{t}",
        "CSP_lam10_y_CALIB": r"\Delta \lambda_{y}",
        "CSP_lam10_z_CALIB": r"\Delta \lambda_{z}",
        "CSP_lam10_A_CALIB": r"\Delta \lambda_{A}",
        "CSP_lam10_u_CALIB": r"\Delta \lambda_{u}",
        "CSP_lam10_v_CALIB": r"\Delta \lambda_{v}",
        "CFAK_lam10_gl_CALIB": r"\Delta \lambda_{gl}",
        "CFAK_lam10_hm_CALIB": r"\Delta \lambda_{hm}",
        "CFAK_lam10_in_CALIB": r"\Delta \lambda_{in}",
        "CFAK_lam10_jo_CALIB": r"\Delta \lambda_{jo}",
        "CFAF_lam10_p_CALIB": r"\Delta \lambda_{p}",
        "CFAF_lam10_q_CALIB": r"\Delta \lambda_{q}",
        "CFAF_lam10_r_CALIB": r"\Delta \lambda_{r}",
        "CFAF_lam10_s_CALIB": r"\Delta \lambda_{s}",
        "CFAS_lam10_c_CALIB": r"\Delta \lambda_{c}",
        "CFAS_lam10_d_CALIB": r"\Delta \lambda_{d}",
        "CFAS_lam10_e_CALIB": r"\Delta \lambda_{e}",
        "CFAO_lam10_CH_CALIB": r"\Delta \lambda_{CH}",
        "CFAO_lam10_DI_CALIB": r"\Delta \lambda_{DI}",
        "CFAO_lam10_EJ_CALIB": r"\Delta \lambda_{EJ}",
        "CFAO_lam10_FK_CALIB": r"\Delta \lambda_{FK}",
    }
    return res