
def get_systematic_mapping():
    res = {
        "HST_cal": r"{\rm HST Calib}",
        "VPEC": r"v_{\rm pec}",
        "SALT20_cal": r"{\rm SALT}_0",
        "SALT21_cal": r"{\rm SALT}_1",
        "SALT22_cal": r"{\rm SALT}_2",
        "SALT23_cal": r"{\rm SALT}_3",
        "SALT24_cal": r"{\rm SALT}_4",
        "SALT25_cal": r"{\rm SALT}_5",
        "SALT26_cal": r"{\rm SALT}_6",
        "SALT27_cal": r"{\rm SALT}_7",
        "SALT28_cal": r"{\rm SALT}_8",
        "SALT29_cal": r"{\rm SALT}_9",
        "MWEBV": r"{\rm MWE}_{B-V}",
        "SF2011-MWEBV": r"{\rm MWE Model}",
        "Fitz99ColorLaw": r"{\rm MWE ColorLaw}",
        "OD94ColorLaw": r"{\rm MWE ColorLaw}",
        "REDSHIFT_BIAS": r"{\rm \delta z }",
        "DES_ZP_g_survcal": r"\Delta g",
        "DES_ZP_r_survcal": r"\Delta r",
        "DES_ZP_i_survcal": r"\Delta i",
        "DES_ZP_z_survcal": r"\Delta z",
        "DES_wave_g_survcal": r"\Delta \lambda_g",
        "DES_wave_r_survcal": r"\Delta \lambda_r",
        "DES_wave_i_survcal": r"\Delta \lambda_i",
        "DES_wave_z_survcal": r"\Delta \lambda_z",
        "CSP_ZP_t_survcal": r"\Delta t",
        "CSP_ZP_y_survcal": r"\Delta y",
        "CSP_ZP_z_survcal": r"\Delta Z",
        "CSP_ZP_A_survcal": r"\Delta A",
        "CSP_ZP_u_survcal": r"\Delta u",
        "CSP_ZP_v_survcal": r"\Delta v",
        "CFAK_ZP_gl_survcal": r"\Delta gl",
        "CFAK_ZP_hm_survcal": r"\Delta hm",
        "CFAK_ZP_in_survcal": r"\Delta in",
        "CFAK_ZP_jo_survcal": r"\Delta jo",
        "CFAF_ZP_p_survcal": r"\Delta p",
        "CFAF_ZP_q_survcal": r"\Delta q",
        "CFAF_ZP_r_survcal": r"\Delta R",
        "CFAF_ZP_s_survcal": r"\Delta s",
        "CFAS_ZP_b_survcal": r"\Delta b",
        "CFAS_ZP_c_survcal": r"\Delta c",
        "CFAS_ZP_d_survcal": r"\Delta d",
        "CFAS_ZP_e_survcal": r"\Delta e",
        "CFAO_ZP_CH_survcal": r"\Delta CH",
        "CFAO_ZP_DI_survcal": r"\Delta DI",
        "CFAO_ZP_EJ_survcal": r"\Delta EJ",
        "CFAO_ZP_FK_survcal": r"\Delta FK",
        "CSP_wave_t_survcal": r"\Delta \lambda_{t}",
        "CSP_wave_y_survcal": r"\Delta \lambda_{y}",
        "CSP_wave_z_survcal": r"\Delta \lambda_{z}",
        "CSP_wave_A_survcal": r"\Delta \lambda_{A}",
        "CSP_wave_u_survcal": r"\Delta \lambda_{u}",
        "CSP_wave_v_survcal": r"\Delta \lambda_{v}",
        "CFAK_WAVE_gl_survcal": r"\Delta \lambda_{gl}",
        "CFAK_WAVE_hm_survcal": r"\Delta \lambda_{hm}",
        "CFAK_WAVE_in_survcal": r"\Delta \lambda_{in}",
        "CFAK_WAVE_jo_survcal": r"\Delta \lambda_{jo}",
        "CFAF_WAVE_p_survcal": r"\Delta \lambda_{p}",
        "CFAF_WAVE_q_survcal": r"\Delta \lambda_{q}",
        "CFAF_WAVE_r_survcal": r"\Delta \lambda_{r}",
        "CFAF_WAVE_s_survcal": r"\Delta \lambda_{s}",
        "CFAS_WAVE_b_survcal": r"\Delta \lambda_{b}",
        "CFAS_WAVE_c_survcal": r"\Delta \lambda_{c}",
        "CFAS_WAVE_d_survcal": r"\Delta \lambda_{d}",
        "CFAS_WAVE_e_survcal": r"\Delta \lambda_{e}",
        "CFAO_wave_CH_survcal": r"\Delta \lambda_{CH}",
        "CFAO_wave_DI_survcal": r"\Delta \lambda_{DI}",
        "CFAO_wave_EJ_survcal": r"\Delta \lambda_{EJ}",
        "CFAO_wave_FK_survcal": r"\Delta \lambda_{FK}",
    }
    return res