python approximate_systematic_0_test.py
sleep 1
python approximate_systematic_1_test.py
sleep 1
python approximate_systematic_2_test.py
sleep 1
python approximate_systematic_3_test.py
sleep 1
python approximate_systematic_4_test.py
sleep 1
python approximate_systematic_5_test.py
sleep 1
python approximate_systematic_6_test.py
